default: &default
  pipelines: "*"
  logger:
    level: 1
    source: default
  job_worker:
    count: <%= ENV.fetch("DUCTWORK_JOB_WORKER_COUNT", 10).to_i %>
    max_retry: 3
    polling_timeout: 1
    shutdown_timeout: 20
  pipeline_advancer:
    polling_timeout: 1
    shutdown_timeout: 20
    steps:
      max_depth: -1
  supervisor:
    polling_timeout: 1
    shutdown_timeout: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
